c1_tenants:
  CUSTOMER1:
    enable_mlag_ibgp_peering_vrfs: false
    mac_vrf_id_base: 10000
    mac_vrf_vni_base: 10000
    vrfs:
      C1_VRF1:
        additional_route_targets:
        - address_family: vpn-ipv4
          nodes:
          - dc1-el1
          - dc1-el2
          - dc1-el3
          - dc2-el1
          - dc2-el2
          - dc2-el3
          route_target: '65001:10'
          type: export
        - address_family: vpn-ipv4
          nodes:
          - dc1-el1
          - dc1-el2
          - dc1-el3
          - dc2-el1
          - dc2-el2
          - dc2-el3
          route_target: '65001:10'
          type: import
        address_families:
        - vpn-ipv4
        - evpn
        l3_interfaces:
        - description: C1-BRANCH1-CPE1
          enabled: true
          interfaces:
          - Ethernet2
          ip_addresses:
          - 172.16.0.1/31
          nodes:
          - branch1-pe1
          ospf:
            enabled: true
        ospf:
          enabled: true
          nodes:
          - branch1-pe1
        svis:
          10:
            enabled: true
            ip_address_virtual: 10.1.10.1/24
            name: C1_10
            tags:
            - dc
        vrf_id: 10
