core_interfaces:
  p2p_links:
  - id: 1
    interfaces:
    - Ethernet1
    - Ethernet4
    nodes:
    - s1-p1
    - dc1-el1
    profile: edgeleaf_uplink_profile
  - id: 2
    interfaces:
    - Ethernet2
    - Ethernet4
    nodes:
    - s1-p1
    - dc1-el2
    profile: edgeleaf_uplink_profile
  - id: 3
    interfaces:
    - Ethernet3
    - Ethernet4
    nodes:
    - s1-p1
    - dc1-el3
    profile: edgeleaf_uplink_profile
  - id: 4
    interfaces:
    - Ethernet4
    - Ethernet4
    nodes:
    - s1-p1
    - s1-p2
    profile: default_core_profile
  - id: 5
    interfaces:
    - Ethernet5
    - Ethernet5
    nodes:
    - s1-p1
    - s1-p3
    profile: default_core_profile
  - id: 6
    interfaces:
    - Ethernet6
    - Ethernet6
    nodes:
    - s1-p1
    - s1-p4
    profile: default_core_profile
  - id: 7
    nodes:
    - s1-p1
    - s2-p1
    port_channel:
      mode: active
      nodes_child_interfaces:
        s1-p1:
        - Ethernet7
        - Ethernet8
        s2-p1:
        - Ethernet7
        - Ethernet8
    profile: default_core_profile
  - id: 8
    interfaces:
    - Ethernet1
    - Ethernet5
    nodes:
    - s1-p2
    - dc1-el1
    profile: edgeleaf_uplink_profile
  - id: 9
    interfaces:
    - Ethernet2
    - Ethernet5
    nodes:
    - s1-p2
    - dc1-el2
    profile: edgeleaf_uplink_profile
  - id: 10
    interfaces:
    - Ethernet3
    - Ethernet5
    nodes:
    - s1-p2
    - dc1-el3
    profile: edgeleaf_uplink_profile
  - id: 11
    interfaces:
    - Ethernet5
    - Ethernet6
    nodes:
    - s1-p2
    - s1-p3
    profile: default_core_profile
  - id: 12
    interfaces:
    - Ethernet6
    - Ethernet5
    nodes:
    - s1-p2
    - s1-p4
    profile: default_core_profile
  - id: 13
    nodes:
    - s1-p2
    - s2-p2
    port_channel:
      mode: active
      nodes_child_interfaces:
        s1-p2:
        - Ethernet7
        - Ethernet8
        s2-p2:
        - Ethernet7
        - Ethernet8
    profile: default_core_profile
  - id: 14
    interfaces:
    - Ethernet1
    - Ethernet1
    nodes:
    - s1-p3
    - s1-edge-pe1
    profile: default_core_profile
  - id: 15
    interfaces:
    - Ethernet2
    - Ethernet1
    nodes:
    - s1-p3
    - s1-edge-pe2
    profile: default_core_profile
  - id: 16
    interfaces:
    - Ethernet3
    - Ethernet3
    nodes:
    - s1-p3
    - s1-p4
    profile: default_core_profile
  - id: 17
    interfaces:
    - Ethernet4
    - Ethernet1
    nodes:
    - s1-p3
    - branch2-pe1
    profile: default_core_profile
  - id: 18
    interfaces:
    - Ethernet1
    - Ethernet2
    nodes:
    - s1-p4
    - s1-edge-pe1
    profile: default_core_profile
  - id: 19
    interfaces:
    - Ethernet2
    - Ethernet2
    nodes:
    - s1-p4
    - s1-edge-pe2
    profile: default_core_profile
  - id: 20
    interfaces:
    - Ethernet4
    - Ethernet1
    nodes:
    - s1-p4
    - branch1-pe1
    profile: default_core_profile
  - id: 21
    interfaces:
    - Ethernet1
    - Ethernet4
    nodes:
    - s2-p1
    - dc2-el1
    profile: edgeleaf_uplink_profile
  - id: 22
    interfaces:
    - Ethernet2
    - Ethernet4
    nodes:
    - s2-p1
    - dc2-el2
    profile: edgeleaf_uplink_profile
  - id: 23
    interfaces:
    - Ethernet3
    - Ethernet4
    nodes:
    - s2-p1
    - dc2-el3
    profile: edgeleaf_uplink_profile
  - id: 24
    interfaces:
    - Ethernet4
    - Ethernet4
    nodes:
    - s2-p1
    - s2-p2
    profile: default_core_profile
  - id: 25
    interfaces:
    - Ethernet5
    - Ethernet5
    nodes:
    - s2-p1
    - s2-p3
    profile: default_core_profile
  - id: 26
    interfaces:
    - Ethernet6
    - Ethernet6
    nodes:
    - s2-p1
    - s2-p4
    profile: default_core_profile
  - id: 27
    interfaces:
    - Ethernet1
    - Ethernet5
    nodes:
    - s2-p2
    - dc2-el1
    profile: edgeleaf_uplink_profile
  - id: 28
    interfaces:
    - Ethernet2
    - Ethernet5
    nodes:
    - s2-p2
    - dc2-el2
    profile: edgeleaf_uplink_profile
  - id: 29
    interfaces:
    - Ethernet3
    - Ethernet5
    nodes:
    - s2-p2
    - dc2-el3
    profile: edgeleaf_uplink_profile
  - id: 30
    interfaces:
    - Ethernet5
    - Ethernet6
    nodes:
    - s2-p2
    - s2-p3
    profile: default_core_profile
  - id: 31
    interfaces:
    - Ethernet6
    - Ethernet5
    nodes:
    - s2-p2
    - s2-p4
    profile: default_core_profile
  - id: 32
    interfaces:
    - Ethernet1
    - Ethernet1
    nodes:
    - s2-p3
    - s2-edge-pe1
    profile: default_core_profile
  - id: 33
    interfaces:
    - Ethernet2
    - Ethernet1
    nodes:
    - s2-p3
    - s2-edge-pe2
    profile: default_core_profile
  - id: 34
    interfaces:
    - Ethernet3
    - Ethernet3
    nodes:
    - s2-p3
    - s2-p4
    profile: default_core_profile
  - id: 35
    interfaces:
    - Ethernet4
    - Ethernet1
    nodes:
    - s2-p3
    - branch3-pe1
    profile: default_core_profile
  - id: 36
    interfaces:
    - Ethernet1
    - Ethernet2
    nodes:
    - s2-p4
    - s2-edge-pe1
    profile: default_core_profile
  - id: 37
    interfaces:
    - Ethernet2
    - Ethernet2
    nodes:
    - s2-p4
    - s2-edge-pe2
    profile: default_core_profile
  - id: 38
    interfaces:
    - Ethernet4
    - Ethernet1
    nodes:
    - s2-p4
    - branch3-pe2
    profile: default_core_profile
  - id: 39
    interfaces:
    - Ethernet2
    - Ethernet2
    nodes:
    - branch3-pe1
    - branch3-pe2
    profile: default_core_profile
  p2p_links_ip_pools:
  - ipv4_pool: 100.65.1.0/24
    name: core_pool
  p2p_links_profiles:
  - ip_pool: core_pool
    ipv6_enable: true
    isis_authentication_key: $1c$sTNAlR6rKSw=
    isis_authentication_mode: md5
    isis_circuit_type: level-2
    isis_hello_padding: false
    isis_metric: 50
    mtu: 1500
    name: default_core_profile
  - include_in_underlay_protocol: false
    ip_pool: core_pool
    mtu: 1500
    name: edgeleaf_uplink_profile
    raw_eos_cli: 'mpls ip

      isis enable CORE

      isis circuit-type level-2

      isis metric 50

      isis authentication mode md5

      isis authentication key 7 $1c$sTNAlR6rKSw=

      isis network point-to-point

      '
