---
- name: Build Switch configuration
  hosts: COMMON_SETTINGS
  connection: local
  gather_facts: false

  tasks:
    - name: generate intended variables
      import_role:
        name: act-topgen
      vars:
        structured_folder: "intended/structured_configs/"
        # act_add_cvp: false
        # avd_structured_config_file_format: yml
        # output_folder: "act/"




